spring.application.name=backend
# Basic Remote MongoDB Connection URI
spring.mongodb.uri=mongodb://mongo:cyLCjUTNrzcFqMdaNTaAnAmZAyqUMyNJ@hopper.proxy.rlwy.net:35984/miApp?authSource=admin
app.mongodb.database=miApp

# Allowed origin for the Angular dev server
app.cors.allowed-origin=http://localhost:4201
